using System;
using System.Drawing;
using System.IO;
using System.Reflection;
using APV.Common.Extensions;
using APV.GraphicsLibrary;

namespace APV.Pottle.UnitTest.Resources
{
    public static class ResourceManager
    {
        private static byte[] LoadDataFromResource(string name)
        {
            if (string.IsNullOrEmpty(name))
                throw new ArgumentNullException("name");

            Type type = typeof(ResourceManager);
            Assembly assembly = type.Assembly;
            string resourceNamespace = type.Namespace;
            string resourceName = string.Format("{0}.{1}", resourceNamespace, name);
            using (Stream stream = assembly.GetManifestResourceStream(resourceName))
            {
                if (stream == null)
                    throw new ArgumentOutOfRangeException("name", string.Format("Unknown resource name \"{0}\".", name));

                return stream.ToByteArray();
            }
        }

        private static Image LoadImageFromResource(string name)
        {
            byte[] data = LoadDataFromResource(name);
            return data.ToImage();
        }

        public static readonly Image TestIcon = LoadImageFromResource("TestIcon.ico");

        public static readonly Image TestLogo = LoadImageFromResource("TestLogo.png");

        public static readonly byte[] Ai10091191R = LoadDataFromResource("AI10091-191-R.jpg");

        public const string TestIconData = @"AAABAAIAEBAAAAAAAABoBQAAJgAAACAgAAAAAAAAqAgAAI4FAAAoAAAAEAAAACAAAAABAAgAAAAAAEABAAAAAAAAAAAAAAAAAAAAAAAAAAAAADMzMwBmZmYAmZmZAKCgoADAwMAAzMzMANjY2ADo6OgA8PDwAP///wCQkJgAmJigAGhokABwcJgAeHigAGZmmQC4uNAAaGigAHBwqABQUJAAYGCoADMzZgBISJAAmZnMAEBAmABAQKAAODiQAEBAsAAzM5kAZmbMACgooAAzM8wAKCi4ABgYkAAYGKgAEBC4ABAQwAAICKAACAjAAAAAMwAAAGYAAACZAAAAoAAAAKgAAAC4AAAAwAAAAMgAAADMAAAA0AAAANgAAADoAPDw/wAQGKgAADPMADNmzAAAM5kAM2aZAGaZzAAAM2YAAGbMALjI0AAzmcwAAGaZAACZzADAyMgA4OjoAGaZmQAzZmYAmczMADOZmQBmzMwAM8zMAAAzMwAAZmYAAJmZAADMzADw//8AAP/MAADMmQAzzJkAAJlmAAD/mQAzmWYAZsyZAABmMwAAzGYAM/+ZAAD/ZgAzzGYAAJkzAGb/mQAAzDMAM/9mAAD/MwBmmWYAM2YzAJnMmQAzmTMAZsxmADPMMwAAMwAAAGYAAACZAAAAzAAAAP8AADP/MwBm/2YAmf+ZADP/AAAzzAAAZv8zAGbMMwAzmQAAmf9mAGb/AADQ2MgAZpkzAJnMZgAzZgAAZswAAJn/MwDM/5kAmf8AALjAqACZzDMAZpkAAMz/ZgCZzAAAzP8zAMz/AADg4NgAmZlmAPDw6ABmZjMAzMyZAJmZMwDMzGYAzMwzADMzAABmZgAAmZkAAMzMAAD//wAA//8zAP//ZgD//5kA///wAP/MAADMmQAA/8wzAMyZMwCZZgAA/8xmAKiYgAD/mQAAwLiwAJlmMwDMmWYAZjMAAMxmAAD/mTMA/8yZAP9mAAC4qKAAwLCoALCQgADMZjMAmTMAAP+ZZgCoUCgAsIh4AKhYOACoaFAAwGhIAMBYMAC4cFgAoFhAALg4EADMMwAA/2YzAJhgUACYSDAAyFg4ANhQKADoSBgA8FAgAKCAeADAoJgAsHBgAMhQMAC4QCAA4EggAOBAGADoUCgA4DgQAP8zAACgWEgAeDgwANDIyACZZmYAZjMzAMyZmQCZMzMAzGZmAMwzMwAzAAAAZgAAAJkAAADMAAAA/wAAAP8zMwD/ZmYA/5mZAP/MzAD/ADMAzAAzAP8zZgDMM2YAmQAzAP9mmQD/AGYAmTNmAMxmmQBmADMAzABmAP8zmQD/mcwA/wCZAMwzmQCZAGYA/2bMAMwAmQD/M8wA/wDMAJlmmQBmM2YAzJnMAJkzmQDMZswAzDPMADMAMwBmAGYAmQCZAMwAzACZAMwAmTPMAGYAmQBmM5kAmWbMADMAZgBmAMwAZjPMADMAmQAYAGAAMwDMAAoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCoWTCgkKCoUKCkIICgoKCggiLAQmHwYqG6qyssUKCgoIIzMOJzELMjHGtLmtTQoKCRoyDyEyBC8vfLjAnAoKCgoVMhMcMgQlL3S+uZwKCgoJEjIfHzIUJS89t8GkCgoKESszLjEzLTMyPa65vAoKCggPLBcZLA01/pqwuaa7pAoKCoOTCgcKCqynxbq1v70ICgoKCgoKCgqrucC6wsGrCQoKCgoKCgoKB7bFxcW2xwoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoAAP//AAD//wAA//8AAP//AAD//wAA//8AAP//AAD//wAA//8AAP//AAD//wAA//8AAP//AAD//wAA//8AAP//KAAAACAAAABAAAAAAQAIAAAAAACABAAAAAAAAAAAAAAAAQAAAAAAAAAAAACAAIAAgAAAAICAAAAAgAAAAICAAAAAgADAwMAAwNzAAPDKpgCAgIAA/wD/AP8AAAD//wAAAP8AAAD//wAAAP8A////APD7/wCkoKAA1PD/ALHi/wCO1P8Aa8b/AEi4/wAlqv8AAKr/AACS3AAAerkAAGKWAABKcwAAMlAA1OP/ALHH/wCOq/8Aa4//AEhz/wAlV/8AAFX/AABJ3AAAPbkAADGWAAAlcwAAGVAA1NT/ALGx/wCOjv8Aa2v/AEhI/wAlJf8AAAD/AAAA3AAAALkAAACWAAAAcwAAAFAA49T/AMex/wCrjv8Aj2v/AHNI/wBXJf8AVQD/AEkA3AA9ALkAMQCWACUAcwAZAFAA8NT/AOKx/wDUjv8Axmv/ALhI/wCqJf8AqgD/AJIA3AB6ALkAYgCWAEoAcwAyAFAA/9T/AP+x/wD/jv8A/2v/AP9I/wD/Jf8A/wD/ANwA3AC5ALkAlgCWAHMAcwBQAFAA/9TwAP+x4gD/jtQA/2vGAP9IuAD/JaoA/wCqANwAkgC5AHoAlgBiAHMASgBQADIA/9TjAP+xxwD/jqsA/2uPAP9IcwD/JVcA/wBVANwASQC5AD0AlgAxAHMAJQBQABkA/9TUAP+xsQD/jo4A/2trAP9ISAD/JSUA/wAAANwAAAC5AAAAlgAAAHMAAABQAAAA/+PUAP/HsQD/q44A/49rAP9zSAD/VyUA/1UAANxJAAC5PQAAljEAAHMlAABQGQAA//DUAP/isQD/1I4A/8ZrAP+4SAD/qiUA/6oAANySAAC5egAAlmIAAHNKAABQMgAA///UAP//sQD//44A//9rAP//SAD//yUA//8AANzcAAC5uQAAlpYAAHNzAABQUAAA8P/UAOL/sQDU/44Axv9rALj/SACq/yUAqv8AAJLcAAB6uQAAYpYAAEpzAAAyUAAA4//UAMf/sQCr/44Aj/9rAHP/SABX/yUAVf8AAEncAAA9uQAAMZYAACVzAAAZUAAA1P/UALH/sQCO/44Aa/9rAEj/SAAl/yUAAP8AAADcAAAAuQAAAJYAAABzAAAAUAAA1P/jALH/xwCO/6sAa/+PAEj/cwAl/1cAAP9VAADcSQAAuT0AAJYxAABzJQAAUBkA1P/wALH/4gCO/9QAa//GAEj/uAAl/6oAAP+qAADckgAAuXoAAJZiAABzSgAAUDIA1P//ALH//wCO//8Aa///AEj//wAl//8AAP//AADc3AAAubkAAJaWAABzcwAAUFAA8vLyAObm5gDa2toAzs7OAMLCwgC2trYAqqqqAJ6engCSkpIAhoaGAHp6egBubm4AYmJiAFZWVgBKSkoAPj4+ADIyMgAmJiYAGhoaAA4ODgAREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREff79/AREff69e0REfP69BER8vn7+/r58xIRERERERHuNjM0NvLuBjM0N+0RNzM1K/iJh4WFhYeJ+xIREREREe4GEDMz+e4GEDM09e0GEDMzN4WFhYWFhYWK7xERERERmDYzMzP8mAYzMzP5mAYzMxA0i4iFhYWFifkRERERERERNzMzMyuYNjMzM/uYBjMzMzbz+oWFhYX7ERERERERERH9MzMzKxErEDMz/RE2MzMz+BH4hYWFhfoREREREREREfozMzM2EfwzMzMrESszMzP6EQqIhYWF+hERERERERER9zMzMzaY+TMzMzYR+zMzM/0R84iFhYX7ERERERERERH1NDMzNe/1MzMzBpj4MzMzNxHwiYWFhZcREREREREREfM0MzM09/czMzM09fczMzM2Ee+JhYWFlxERERERERHz/TQzMzM0BjMzMzM1BjMzMwaMFIqFhYWKEhERERER7f0zMzMzMzMQMzMzMzMzMzMzBu4RioWFhYrtERERERERCgYzMzM0/TQzMzM0/jQzMzMG7xGXhYWFiu4R7e0RERER9Dc0EAaN+DUzMzYI+zQQNon5EfyFhYWJ7u+Li+8RERER7vk3+xER9Cs39BER9iuLhYnw+YWFhYnw9oeI9hEREREREREREREREREREREREoqFh/f4hYWFiPT6hYf57BERERERERERERERERERERER+4WFiYqFhYWFl4iFh/kRERERERERERERERERERERERH3iIWFhYWFhYWFhYWI9REREREREREREREREREREREREe+KhYWFhYWFhYWFhYnvEREREREREREREREREREREREREfeJioqKioqKioqJ+hEREREREREREREREREREREREREREfHvEhQUEhTsIPESERERERERERERERERERERERERERERERERERERERERERERERERERERERERERERERERERERERERERERERERERERERERERERERERERERERERERERERERERERERERERERERERERERERERERERERERERERERERERERERERERERERERERERERERERERERERERERERERERERERERERERERERERERERERAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA=";
    }
}